class Autogenerated {
  String? cODE;
  String? dESCRIPTION;
  DATA? dATA;

  Autogenerated({this.cODE, this.dESCRIPTION, this.dATA});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    cODE = json['CODE'];
    dESCRIPTION = json['DESCRIPTION'];
    dATA = json['DATA'] != null ? DATA.fromJson(json['DATA']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['CODE'] = cODE;
    data['DESCRIPTION'] = dESCRIPTION;
    if (dATA != null) {
      data['DATA'] = dATA!.toJson();
    }
    return data;
  }
}

class DATA {
  Profile? profile;
  List<PendingOrders>? pendingOrders;
  List<ShippedOrders>? shippedOrders;
  List<DeclinedOrders>? declinedOrders;
  PullListSetting? pullListSetting;
  PreviewSetting? previewSetting;
  List<PullListItems>? pullListItems;
  ActiveSettings? activeSettings;
  List<CcList>? ccList;
  List<AddressList>? addressList;
  List<PullListTypes>? pullListTypes;
  List<PullListStoreLocations>? pullListStoreLocations;
  List<PullListShippingFrequency>? pullListShippingFrequency;

  DATA(
      {this.profile,
        this.pendingOrders,
        this.shippedOrders,
        this.declinedOrders,
        this.pullListSetting,
        this.previewSetting,
        this.pullListItems,
        this.activeSettings,
        this.ccList,
        this.addressList,
        this.pullListTypes,
        this.pullListStoreLocations,
        this.pullListShippingFrequency});

  DATA.fromJson(Map<String, dynamic> json) {
    profile =
    json['profile'] != null ? Profile.fromJson(json['profile']) : null;
    if (json['pendingOrders'] != null) {
      pendingOrders = <PendingOrders>[];
      json['pendingOrders'].forEach((v) {
        pendingOrders!.add(PendingOrders.fromJson(v));
      });
    }
    if (json['shippedOrders'] != null) {
      shippedOrders = <ShippedOrders>[];
      json['shippedOrders'].forEach((v) {
        shippedOrders!.add(ShippedOrders.fromJson(v));
      });
    }
    if (json['declinedOrders'] != null) {
      declinedOrders = <DeclinedOrders>[];
      json['declinedOrders'].forEach((v) {
        declinedOrders!.add(DeclinedOrders.fromJson(v));
      });
    }
    pullListSetting = json['pullListSetting'] != null
        ? PullListSetting.fromJson(json['pullListSetting'])
        : null;
    previewSetting = json['previewSetting'] != null
        ? PreviewSetting.fromJson(json['previewSetting'])
        : null;
    if (json['pullListItems'] != null) {
      pullListItems = <PullListItems>[];
      json['pullListItems'].forEach((v) {
        pullListItems!.add(PullListItems.fromJson(v));
      });
    }
    activeSettings = json['activeSettings'] != null
        ? ActiveSettings.fromJson(json['activeSettings'])
        : null;
    if (json['ccList'] != null) {
      ccList = <CcList>[];
      json['ccList'].forEach((v) {
        ccList!.add(CcList.fromJson(v));
      });
    }
    if (json['addressList'] != null) {
      addressList = <AddressList>[];
      json['addressList'].forEach((v) {
        addressList!.add(AddressList.fromJson(v));
      });
    }
    if (json['PullListTypes'] != null) {
      pullListTypes = <PullListTypes>[];
      json['PullListTypes'].forEach((v) {
        pullListTypes!.add(PullListTypes.fromJson(v));
      });
    }
    if (json['PullListStoreLocations'] != null) {
      pullListStoreLocations = <PullListStoreLocations>[];
      json['PullListStoreLocations'].forEach((v) {
        pullListStoreLocations!.add(PullListStoreLocations.fromJson(v));
      });
    }
    if (json['PullListShippingFrequency'] != null) {
      pullListShippingFrequency = <PullListShippingFrequency>[];
      json['PullListShippingFrequency'].forEach((v) {
        pullListShippingFrequency!
            .add(PullListShippingFrequency.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (profile != null) {
      data['profile'] = profile!.toJson();
    }
    if (pendingOrders != null) {
      data['pendingOrders'] =
          pendingOrders!.map((v) => v.toJson()).toList();
    }
    if (shippedOrders != null) {
      data['shippedOrders'] =
          shippedOrders!.map((v) => v.toJson()).toList();
    }
    if (declinedOrders != null) {
      data['declinedOrders'] =
          declinedOrders!.map((v) => v.toJson()).toList();
    }
    if (pullListSetting != null) {
      data['pullListSetting'] = pullListSetting!.toJson();
    }
    if (previewSetting != null) {
      data['previewSetting'] = previewSetting!.toJson();
    }
    if (pullListItems != null) {
      data['pullListItems'] =
          pullListItems!.map((v) => v.toJson()).toList();
    }
    if (activeSettings != null) {
      data['activeSettings'] = activeSettings!.toJson();
    }
    if (ccList != null) {
      data['ccList'] = ccList!.map((v) => v.toJson()).toList();
    }
    if (addressList != null) {
      data['addressList'] = addressList!.map((v) => v.toJson()).toList();
    }
    if (pullListTypes != null) {
      data['PullListTypes'] =
          pullListTypes!.map((v) => v.toJson()).toList();
    }
    if (pullListStoreLocations != null) {
      data['PullListStoreLocations'] =
          pullListStoreLocations!.map((v) => v.toJson()).toList();
    }
    if (pullListShippingFrequency != null) {
      data['PullListShippingFrequency'] =
          pullListShippingFrequency!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Profile {
  String? table1;
  String? shId;
  String? shFname;
  String? shLname;
  String? shLgid;
  String? shDob;

  Profile(
      {this.table1,
        this.shId,
        this.shFname,
        this.shLname,
        this.shLgid,
        this.shDob});

  Profile.fromJson(Map<String, dynamic> json) {
    table1 = json['table-1'];
    shId = json['sh_id'];
    shFname = json['sh_fname'];
    shLname = json['sh_lname'];
    shLgid = json['sh_lgid'];
    shDob = json['sh_dob'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['table-1'] = table1;
    data['sh_id'] = shId;
    data['sh_fname'] = shFname;
    data['sh_lname'] = shLname;
    data['sh_lgid'] = shLgid;
    data['sh_dob'] = shDob;
    return data;
  }
}

class PendingOrders {
  String? table2;
  String? odStmp;
  String? odId;
  String? orderTotal;

  PendingOrders({this.table2, this.odStmp, this.odId, this.orderTotal});

  PendingOrders.fromJson(Map<String, dynamic> json) {
    table2 = json['table-2'];
    odStmp = json['od_stmp'];
    odId = json['od_id'];
    orderTotal = json['order_total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['table-2'] = table2;
    data['od_stmp'] = odStmp;
    data['od_id'] = odId;
    data['order_total'] = orderTotal;
    return data;
  }
}

class ShippedOrders {
  String? table3;
  String? odStmp;
  String? odId;
  String? orderTotal;

  ShippedOrders({this.table3, this.odStmp, this.odId, this.orderTotal});

  ShippedOrders.fromJson(Map<String, dynamic> json) {
    table3 = json['table-3'];
    odStmp = json['od_stmp'];
    odId = json['od_id'];
    orderTotal = json['order_total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['table-3'] = table3;
    data['od_stmp'] = odStmp;
    data['od_id'] = odId;
    data['order_total'] = orderTotal;
    return data;
  }
}

class DeclinedOrders {
  String? table4;
  String? odStmp;
  String? odId;
  String? orderTotal;

  DeclinedOrders({this.table4, this.odStmp, this.odId, this.orderTotal});

  DeclinedOrders.fromJson(Map<String, dynamic> json) {
    table4 = json['table-4'];
    odStmp = json['od_stmp'];
    odId = json['od_id'];
    orderTotal = json['order_total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['table-4'] = table4;
    data['od_stmp'] = odStmp;
    data['od_id'] = odId;
    data['order_total'] = orderTotal;
    return data;
  }
}

class PullListSetting {
  String? table5;
  String? ssId;
  String? ssAdmactive;
  String? pmId;
  String? billcycle;
  String? smId;
  String? saIdShp;
  String? saIdBill;
  String? blname;
  String? bfname;
  String? bcompany;
  String? bpobox;
  String? baddr1;
  String? baddr2;
  String? bmname;
  String? bcity;
  String? bstate;
  String? bzip;
  String? bres;
  String? ssActive;
  String? slname;
  String? sfname;
  String? scompany;
  String? spobox;
  String? smname;
  String? saddr1;
  String? saddr2;
  String? scity;
  String? sstate;
  String? szip;
  String? sres;
  String? pmCardtype;
  String? pmCardnum;
  String? pmExpmnth;
  String? pmExpyear;
  String? bcntry;
  String? scntry;
  String? shipmeth;
  String? ssGroup;
  String? ssLocation;
  String? totalsubtitles;

  PullListSetting(
      {this.table5,
        this.ssId,
        this.ssAdmactive,
        this.pmId,
        this.billcycle,
        this.smId,
        this.saIdShp,
        this.saIdBill,
        this.blname,
        this.bfname,
        this.bcompany,
        this.bpobox,
        this.baddr1,
        this.baddr2,
        this.bmname,
        this.bcity,
        this.bstate,
        this.bzip,
        this.bres,
        this.ssActive,
        this.slname,
        this.sfname,
        this.scompany,
        this.spobox,
        this.smname,
        this.saddr1,
        this.saddr2,
        this.scity,
        this.sstate,
        this.szip,
        this.sres,
        this.pmCardtype,
        this.pmCardnum,
        this.pmExpmnth,
        this.pmExpyear,
        this.bcntry,
        this.scntry,
        this.shipmeth,
        this.ssGroup,
        this.ssLocation,
        this.totalsubtitles});

  PullListSetting.fromJson(Map<String, dynamic> json) {
    table5 = json['table-5'];
    ssId = json['ss_id'];
    ssAdmactive = json['ss_admactive'];
    pmId = json['pm_id'];
    billcycle = json['billcycle'];
    smId = json['sm_id'];
    saIdShp = json['sa_id_shp'];
    saIdBill = json['sa_id_bill'];
    blname = json['blname'];
    bfname = json['bfname'];
    bcompany = json['bcompany'];
    bpobox = json['bpobox'];
    baddr1 = json['baddr1'];
    baddr2 = json['baddr2'];
    bmname = json['bmname'];
    bcity = json['bcity'];
    bstate = json['bstate'];
    bzip = json['bzip'];
    bres = json['bres'];
    ssActive = json['ss_active'];
    slname = json['slname'];
    sfname = json['sfname'];
    scompany = json['scompany'];
    spobox = json['spobox'];
    smname = json['smname'];
    saddr1 = json['saddr1'];
    saddr2 = json['saddr2'];
    scity = json['scity'];
    sstate = json['sstate'];
    szip = json['szip'];
    sres = json['sres'];
    pmCardtype = json['pm_cardtype'];
    pmCardnum = json['pm_cardnum'];
    pmExpmnth = json['pm_expmnth'];
    pmExpyear = json['pm_expyear'];
    bcntry = json['bcntry'];
    scntry = json['scntry'];
    shipmeth = json['shipmeth'];
    ssGroup = json['ss_group'];
    ssLocation = json['ss_location'];
    totalsubtitles = json['totalsubtitles'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['table-5'] = table5;
    data['ss_id'] = ssId;
    data['ss_admactive'] = ssAdmactive;
    data['pm_id'] = pmId;
    data['billcycle'] = billcycle;
    data['sm_id'] = smId;
    data['sa_id_shp'] = saIdShp;
    data['sa_id_bill'] = saIdBill;
    data['blname'] = blname;
    data['bfname'] = bfname;
    data['bcompany'] = bcompany;
    data['bpobox'] = bpobox;
    data['baddr1'] = baddr1;
    data['baddr2'] = baddr2;
    data['bmname'] = bmname;
    data['bcity'] = bcity;
    data['bstate'] = bstate;
    data['bzip'] = bzip;
    data['bres'] = bres;
    data['ss_active'] = ssActive;
    data['slname'] = slname;
    data['sfname'] = sfname;
    data['scompany'] = scompany;
    data['spobox'] = spobox;
    data['smname'] = smname;
    data['saddr1'] = saddr1;
    data['saddr2'] = saddr2;
    data['scity'] = scity;
    data['sstate'] = sstate;
    data['szip'] = szip;
    data['sres'] = sres;
    data['pm_cardtype'] = pmCardtype;
    data['pm_cardnum'] = pmCardnum;
    data['pm_expmnth'] = pmExpmnth;
    data['pm_expyear'] = pmExpyear;
    data['bcntry'] = bcntry;
    data['scntry'] = scntry;
    data['shipmeth'] = shipmeth;
    data['ss_group'] = ssGroup;
    data['ss_location'] = ssLocation;
    data['totalsubtitles'] = totalsubtitles;
    return data;
  }
}

class PreviewSetting {
  String? table6;
  String? ssId;
  String? shId;
  String? saIdBill;
  String? saIdShp;
  String? smId;
  String? billcycle;
  String? ssActive;
  String? ssAdmactive;
  String? pmId;
  String? ssGroup;
  String? shipFulladdress;
  String? billFulladdress;
  String? smDesc;
  String? previewsPendingCount;

  PreviewSetting(
      {this.table6,
        this.ssId,
        this.shId,
        this.saIdBill,
        this.saIdShp,
        this.smId,
        this.billcycle,
        this.ssActive,
        this.ssAdmactive,
        this.pmId,
        this.ssGroup,
        this.shipFulladdress,
        this.billFulladdress,
        this.smDesc,
        this.previewsPendingCount});

  PreviewSetting.fromJson(Map<String, dynamic> json) {
    table6 = json['table-6'];
    ssId = json['ss_id'];
    shId = json['sh_id'];
    saIdBill = json['sa_id_bill'];
    saIdShp = json['sa_id_shp'];
    smId = json['sm_id'];
    billcycle = json['billcycle'];
    ssActive = json['ss_active'];
    ssAdmactive = json['ss_admactive'];
    pmId = json['pm_id'];
    ssGroup = json['ss_group'];
    shipFulladdress = json['ship_fulladdress'];
    billFulladdress = json['bill_fulladdress'];
    smDesc = json['sm_desc'];
    previewsPendingCount = json['previews_pending_count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['table-6'] = table6;
    data['ss_id'] = ssId;
    data['sh_id'] = shId;
    data['sa_id_bill'] = saIdBill;
    data['sa_id_shp'] = saIdShp;
    data['sm_id'] = smId;
    data['billcycle'] = billcycle;
    data['ss_active'] = ssActive;
    data['ss_admactive'] = ssAdmactive;
    data['pm_id'] = pmId;
    data['ss_group'] = ssGroup;
    data['ship_fulladdress'] = shipFulladdress;
    data['bill_fulladdress'] = billFulladdress;
    data['sm_desc'] = smDesc;
    data['previews_pending_count'] = previewsPendingCount;
    return data;
  }
}

class PullListItems {
  String? table7;
  String? prReldt;
  String? shId;
  String? prId;
  String? type;
  String? stat;
  String? prLprice;
  String? prMxqty;
  String? prTtle;
  String? scQty;
  String? cgId;
  String? suId;
  String? fetchtype;
  String? susp;
  String? prConditionflag;
  String? conditionname;
  String? exInRegularOrders;
  String? exInPreviewsOrders;
  String? exInTcart;
  String? sortorder;

  PullListItems(
      {this.table7,
        this.prReldt,
        this.shId,
        this.prId,
        this.type,
        this.stat,
        this.prLprice,
        this.prMxqty,
        this.prTtle,
        this.scQty,
        this.cgId,
        this.suId,
        this.fetchtype,
        this.susp,
        this.prConditionflag,
        this.conditionname,
        this.exInRegularOrders,
        this.exInPreviewsOrders,
        this.exInTcart,
        this.sortorder});

  PullListItems.fromJson(Map<String, dynamic> json) {
    table7 = json['table-7'];
    prReldt = json['pr_reldt'];
    shId = json['sh_id'];
    prId = json['pr_id'];
    type = json['type'];
    stat = json['stat'];
    prLprice = json['pr_lprice'];
    prMxqty = json['pr_mxqty'];
    prTtle = json['pr_ttle'];
    scQty = json['sc_qty'];
    cgId = json['cg_id'];
    suId = json['su_id'];
    fetchtype = json['fetchtype'];
    susp = json['susp'];
    prConditionflag = json['pr_conditionflag'];
    conditionname = json['conditionname'];
    exInRegularOrders = json['ex_in_regular_orders'];
    exInPreviewsOrders = json['ex_in_previews_orders'];
    exInTcart = json['ex_in_tcart'];
    sortorder = json['sortorder'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['table-7'] = table7;
    data['pr_reldt'] = prReldt;
    data['sh_id'] = shId;
    data['pr_id'] = prId;
    data['type'] = type;
    data['stat'] = stat;
    data['pr_lprice'] = prLprice;
    data['pr_mxqty'] = prMxqty;
    data['pr_ttle'] = prTtle;
    data['sc_qty'] = scQty;
    data['cg_id'] = cgId;
    data['su_id'] = suId;
    data['fetchtype'] = fetchtype;
    data['susp'] = susp;
    data['pr_conditionflag'] = prConditionflag;
    data['conditionname'] = conditionname;
    data['ex_in_regular_orders'] = exInRegularOrders;
    data['ex_in_previews_orders'] = exInPreviewsOrders;
    data['ex_in_tcart'] = exInTcart;
    data['sortorder'] = sortorder;
    return data;
  }
}

class ActiveSettings {
  String? shId;
  String? smId;
  String? smDesc;
  String? saId;
  String? billsaId;
  String? shipFulladdress;
  String? billFulladdress;
  String? cardnum;
  String? saidOdcount;
  String? baidOdcount;

  ActiveSettings(
      {this.shId,
        this.smId,
        this.smDesc,
        this.saId,
        this.billsaId,
        this.shipFulladdress,
        this.billFulladdress,
        this.cardnum,
        this.saidOdcount,
        this.baidOdcount});

  ActiveSettings.fromJson(Map<String, dynamic> json) {
    shId = json['sh_id'];
    smId = json['sm_id'];
    smDesc = json['sm_desc'];
    saId = json['sa_id'];
    billsaId = json['billsa_id'];
    shipFulladdress = json['ship_fulladdress'];
    billFulladdress = json['bill_fulladdress'];
    cardnum = json['cardnum'];
    saidOdcount = json['said_odcount'];
    baidOdcount = json['baid_odcount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['sh_id'] = shId;
    data['sm_id'] = smId;
    data['sm_desc'] = smDesc;
    data['sa_id'] = saId;
    data['billsa_id'] = billsaId;
    data['ship_fulladdress'] = shipFulladdress;
    data['bill_fulladdress'] = billFulladdress;
    data['cardnum'] = cardnum;
    data['said_odcount'] = saidOdcount;
    data['baid_odcount'] = baidOdcount;
    return data;
  }
}

class CcList {
  String? pmId;
  String? shId;
  String? firstName;
  String? lastName;
  String? pmCardtype;
  String? pmCardnum;
  String? pmExpmnth;
  String? pmExpyear;
  String? cvv;
  String? isDefault;
  String? isDefaultCardExist;

  CcList(
      {this.pmId,
        this.shId,
        this.firstName,
        this.lastName,
        this.pmCardtype,
        this.pmCardnum,
        this.pmExpmnth,
        this.pmExpyear,
        this.cvv,
        this.isDefault,
        this.isDefaultCardExist});

  CcList.fromJson(Map<String, dynamic> json) {
    pmId = json['pm_id'];
    shId = json['sh_id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    pmCardtype = json['pm_cardtype'];
    pmCardnum = json['pm_cardnum'];
    pmExpmnth = json['pm_expmnth'];
    pmExpyear = json['pm_expyear'];
    cvv = json['cvv'];
    isDefault = json['is_default'];
    isDefaultCardExist = json['is_default_card_exist'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['pm_id'] = pmId;
    data['sh_id'] = shId;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['pm_cardtype'] = pmCardtype;
    data['pm_cardnum'] = pmCardnum;
    data['pm_expmnth'] = pmExpmnth;
    data['pm_expyear'] = pmExpyear;
    data['cvv'] = cvv;
    data['is_default'] = isDefault;
    data['is_default_card_exist'] = isDefaultCardExist;
    return data;
  }
}

class AddressList {
  String? saId;
  String? fullName;
  String? saDesc;
  String? fullAddress;
  String? saType;
  String? isDefault;
  String? saCntry;
  String? fullAddress2;
  String? saFname;
  String? saLname;
  String? saCmpny;
  String? saAddr1;
  String? saAddr2;
  String? saPhone1;
  String? saCity;
  String? saZip;
  String? saState;
  String? saCntry1;
  String? countryName;
  String? saPobox;
  String? saDeliveryInstructions;
  String? ordcount;
  String? addrcount;
  String? shipordcount;

  AddressList(
      {this.saId,
        this.fullName,
        this.saDesc,
        this.fullAddress,
        this.saType,
        this.isDefault,
        this.saCntry,
        this.fullAddress2,
        this.saFname,
        this.saLname,
        this.saCmpny,
        this.saAddr1,
        this.saAddr2,
        this.saPhone1,
        this.saCity,
        this.saZip,
        this.saState,
        this.saCntry1,
        this.countryName,
        this.saPobox,
        this.saDeliveryInstructions,
        this.ordcount,
        this.addrcount,
        this.shipordcount});

  AddressList.fromJson(Map<String, dynamic> json) {
    saId = json['sa_id'];
    fullName = json['full_name'];
    saDesc = json['sa_desc'];
    fullAddress = json['full_address'];
    saType = json['sa_type'];
    isDefault = json['is_default'];
    saCntry = json['sa_cntry'];
    fullAddress2 = json['full_address2'];
    saFname = json['sa_fname'];
    saLname = json['sa_lname'];
    saCmpny = json['sa_cmpny'];
    saAddr1 = json['sa_addr1'];
    saAddr2 = json['sa_addr2'];
    saPhone1 = json['sa_phone1'];
    saCity = json['sa_city'];
    saZip = json['sa_zip'];
    saState = json['sa_state'];
    saCntry1 = json['sa_cntry1'];
    countryName = json['country_name'];
    saPobox = json['sa_pobox'];
    saDeliveryInstructions = json['sa_delivery_instructions'];
    ordcount = json['ordcount'];
    addrcount = json['addrcount'];
    shipordcount = json['shipordcount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['sa_id'] = saId;
    data['full_name'] = fullName;
    data['sa_desc'] = saDesc;
    data['full_address'] = fullAddress;
    data['sa_type'] = saType;
    data['is_default'] = isDefault;
    data['sa_cntry'] = saCntry;
    data['full_address2'] = fullAddress2;
    data['sa_fname'] = saFname;
    data['sa_lname'] = saLname;
    data['sa_cmpny'] = saCmpny;
    data['sa_addr1'] = saAddr1;
    data['sa_addr2'] = saAddr2;
    data['sa_phone1'] = saPhone1;
    data['sa_city'] = saCity;
    data['sa_zip'] = saZip;
    data['sa_state'] = saState;
    data['sa_cntry1'] = saCntry1;
    data['country_name'] = countryName;
    data['sa_pobox'] = saPobox;
    data['sa_delivery_instructions'] = saDeliveryInstructions;
    data['ordcount'] = ordcount;
    data['addrcount'] = addrcount;
    data['shipordcount'] = shipordcount;
    return data;
  }
}

class PullListTypes {
  String? subType;
  String? subTypeName;

  PullListTypes({this.subType, this.subTypeName});

  PullListTypes.fromJson(Map<String, dynamic> json) {
    subType = json['sub_type'];
    subTypeName = json['sub_type_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['sub_type'] = subType;
    data['sub_type_name'] = subTypeName;
    return data;
  }
}

class PullListStoreLocations {
  String? ssLocation;
  String? ssLocationAddress;

  PullListStoreLocations({this.ssLocation, this.ssLocationAddress});

  PullListStoreLocations.fromJson(Map<String, dynamic> json) {
    ssLocation = json['ss_location'];
    ssLocationAddress = json['ss_location_address'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['ss_location'] = ssLocation;
    data['ss_location_address'] = ssLocationAddress;
    return data;
  }
}

class PullListShippingFrequency {
  String? ssbillcycle;
  String? ssbillcycleValue;

  PullListShippingFrequency({this.ssbillcycle, this.ssbillcycleValue});

  PullListShippingFrequency.fromJson(Map<String, dynamic> json) {
    ssbillcycle = json['ssbillcycle'];
    ssbillcycleValue = json['ssbillcycle_value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['ssbillcycle'] = ssbillcycle;
    data['ssbillcycle_value'] = ssbillcycleValue;
    return data;
  }
}